rootProject.name = "TotalArab"

// Arabic content providers.
include("AkwamProvider")
include("WeCimaProvider")
include("MyCimaProvider")
include("FaselhdProvider")
include("TVgardenProvider")
include("CimalightProvider")
include("Anime4upProvider")
include("DimaToonProvider")
include("TuktukcimaProvider")
include("SyrialiveProvider")
include("ViuProvider")
include("TuniflixProvider")
include("CimatnProvider")
include("CeeProvider")
include("Anime3rbProvider")
include("YoutubeProvider")
include("LodynetProvider")
include("MarocLiveProvider")
include("TopcinemaProvider")
include("ReplaymatchProvider")
include("BristegeProvider")
include("AnimewitcherProvider")
include("EgydeadProvider")
include("Asia2tv2Provider")
include("ThreeiskProvider")
include("EseekProvider")
include("KrmzyProvider")
include("AnimercoProvider")
include("WitanimeProvider")
include("Shahid4uProvider")
include("CimaClubProvider")
include("CimawbasProvider")
include("ArabseedProvider")
include("CinemanaProvider")
